version: "2.3"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./setup/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    ports:
      - "8080:80"
    networks:
      - mynet
  php:
    build:
      context: .
      dockerfile: Phpdockerfile
    networks:
      - mynet
  database:
    container_name: maria_librarian
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: n130177
      MARIADB_DATABASE: librarian
      MARIADB_USER: root
      MARIADB_PASSWORD: n130177
    ports:
      - "9907:3306"
    volumes:
      - ./setup/librarian.sql:/docker-entrypoint-initdb.d/init.sql
      - mydb:/var/lib/mysql
    networks:
      - mynet
networks:
  mynet:
volumes:
  mydb: